### ISSUE TITLE
Document downstream delete annotation

### ISSUE THREAD

**Issue by mhrivnak** [openshift/cluster-api-provider-baremetal#46]
We need to document somewhere that in downstream, the annotation to put on a Machine when you want it to be deleted during a MachineSet scale-down is `machine.openshift.io/cluster-api-delete-machine=yes`.

**Comment by russellb** [comment]
Sounds like something to file against the machine-api-operator?  or perhaps in JIRA in the cloud team's backlog to document somewhere appropriately?  or if you're feeling ambitious, a patch to https://github.com/openshift/openshift-docs ?

**Comment by enxebre** [comment]
FYI this is documented here https://docs.openshift.com/container-platform/4.4/machine_management/manually-scaling-machineset.html

**Comment by zaneb** [comment]
Looks like it is documented in the right place, so let's close this.
/close
