### ISSUE TITLE
Deleting a Host doesn't immediately affect Machine

### ISSUE THREAD

**Issue by zaneb** [openshift/cluster-api-provider-baremetal#56]
When a BareMetalHost is marked for deletion, it doesn't enter the `deleting` provisioning state until it has been deprovisioned (if necessary). When a Host is deleted, we don't currently delete the Machine until the Host reaches that state. This means that if the Host was provisioned, the Machine will to all outward appearances seem healthy until the Host is fully deprovisioned. If the cluster is scaled down in the meantime (an obvious thing to do when removing a Host from inventory), the MachineSet will remove a random Machine rather than necessarily the one whose Host is going away.

**Comment by mhrivnak** [comment]
Machines don't really have a notion of health, do they? Perhaps we are giving the wrong impression somewhere about that?

We could use the [`Phase`](https://github.com/openshift/cluster-api/blob/b2c5ded/pkg/apis/machine/v1beta1/machine_types.go#L175) possibly to better communicate what's going on.

**Comment by mhrivnak** [comment]
Deleting the Machine sooner won't help the scaling-down part. If you delete the Machine earlier in the workflow, the MachineSet controller is just going to create a new one. Then if you scale down the MachineSet, it may not pick that Machine as the one to delete and may still delete a Machine with a healthy Node.

The way to safely scale down is documented here: https://github.com/metal3-io/metal3-docs/blob/master/design/remove-host.md

**Comment by zaneb** [comment]
@mhrivnak are you saying that the MachineSet doesn't even look at the Phase and prioritise keeping the Running Machines? That seems like a missed opportunity at best...

**Comment by zaneb** [comment]
Changing the phase to Failed automatically sets ErrorMessage. (And, strangely, the ErrorReason doesn't appear to ever be set, even when the reason is known (like InvalidConfigurationMachineError). So Failed Machines will in fact be prioritised for removal in practice.

Going into the Failed phase also sets the annotation `machine.openshift.io/instance-state=Unknown`, although this doesn't appear to be used by the MachineSet.
